### ISSUE TITLE
Failed to resolve glXGetProcAddress

### ISSUE THREAD

**Issue by Arisa-Snowbell** [nowrep/obs-vkcapture#190]
**Describe the bug**
Minecraft errors out with "GLFW error 65543: GLX: Forward compatibility requested but GLX_ARB_create_context_profile is unavailable." if I use obs-gamecapture.

**System (please complete the following information):**
 - OS: Linux
 - GPU: NVIDIA 1080TI
 - Mesa version: 1:23.2.1-2
 - obs-vkcapture version: r297.39db320-1
 - Wayland

**Game log:**
```
[obs-vkcapture] Init GLX 1.4.7 (64bit)
[obs-vkcapture] Failed to resolve glXGetProcAddress
[21:25:30] [Render thread/WARN]: Failed to create window: 
ekt$a: GLFW error 65543: GLX: Forward compatibility requested but GLX_ARB_create_context_profile is unavailable
	at ekt.b(SourceFile:195) ~[minecraft-1.20.2-client.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:build 13]
	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.3.2.jar:build 13]
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058) ~[lwjgl-glfw-3.3.2.jar:build 13]
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229) ~[lwjgl-glfw-3.3.2.jar:build 13]
	at ekt.<init>(SourceFile:93) ~[minecraft-1.20.2-client.jar:?]
	at fow.a(SourceFile:21) ~[minecraft-1.20.2-client.jar:?]
	at eqv.<init>(SourceFile:494) ~[minecraft-1.20.2-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:214) ~[minecraft-1.20.2-client.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

**Additional info:**
```
[21:25:16] [Render thread/INFO]: Backend library: LWJGL version 3.3.2+13
```

**Comment by Arisa-Snowbell** [comment]
**More maybe useful info:**
```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 535.113.01
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 535.113.01
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 535.113.01
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by nowrep** [comment]
I assume it works on 50547aa61993ddb88e325f0dc34fc106b6795d18, correct?

**Comment by nowrep** [comment]
Can you please try this patch?

```diff
diff --git a/src/glinject.c b/src/glinject.c
index 585abe0..df5be6a 100644
--- a/src/glinject.c
+++ b/src/glinject.c
@@ -132,7 +132,11 @@ static bool gl_init_funcs(bool glx)
     data.glx = glx;
 
     if (glx) {
-        void *handle = NULL;
+        void *handle = dlopen("libGLX.so.0", RTLD_LAZY);
+        if (!handle) {
+            hlog("Failed to open libGLX.so.0");
+            return false;
+        }
         GETGLXADDR(GetProcAddress);
         GETGLXADDR(GetProcAddressARB);
         GETGLXPROCADDR(DestroyContext);
```

**Comment by Arisa-Snowbell** [comment]
That patched fixed it
