### ISSUE TITLE
Minecraft (java edition) doesn't start

### ISSUE THREAD

**Issue by MrSn0wy** [nowrep/obs-vkcapture#216]
**Describe the bug**
I'm trying to use obs-vkcapture on minecraft (java edition) using a newer version of GLFW (3.4-2) so i can use native wayland. 
Without obs-vkcapture it works and i can play minecraft natively on wayland, however when i start it with obs-vkCapture i get the following error:
``java.lang.IllegalStateException: Core OpenGL functions could not be found. Make sure that the OpenGL library has been loaded correctly.``

IT does work when i use the built-in GLFW, maybe this is an incompatibility with the newer version?

**Screenshots or video**
Not relevant? (i think)

**System (please complete the following information):**
 - OS: Arch Linux x86_64 (6.9.7-arch1-1)
 - GPU: NVIDIA GeForce GTX 1650 (driver: 555.58.02-1)
 - Mesa version: 1:24.1.2-1
 - obs-vkcapture version: 1.5.0-1 (from the aur)

**OBS log:**
```
Not relevant since it can't even start the game x3
```

**Game log:**
```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-07-05 14:35:21
Description: Initializing game

java.lang.IllegalStateException: Core OpenGL functions could not be found. Make sure that the OpenGL library has been loaded correctly.
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:358)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:311)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:295)
	at fam.<init>(SourceFile:112)
	at gfr.a(SourceFile:21)
	at fgo.<init>(SourceFile:505)
	at net.minecraft.client.main.Main.main(SourceFile:239)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:358)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:311)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:295)
	at fam.<init>(SourceFile:112)
	at gfr.a(SourceFile:21)
	at fgo.<init>(SourceFile:505)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:239)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (amd64) version 6.9.7-arch1-1
	Java Version: 21.0.3, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 381987136 bytes (364 MiB) / 587202560 bytes (560 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: TU116 [GeForce GTX 1650]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MiB): 288.00
	Graphics card #0 deviceId: 0x2188
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 24342.23
	Virtual memory used (MiB): 9426.33
	Swap memory total (MiB): 16384.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 7930.92, total: 7958.24
	Space in storage for workdir (MiB): available: 193066.80, total: 1876686.63
	JVM Flags: 2 total; -Xms512m -Xmx12288m
	Launched Version: 1.21
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3+5
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: wayland
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Probably not. Client jar signature and brand is untouched
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: <unknown>
```

**Comment by Znojmok** [comment]
I have the same problem. I have an AMD GPU so i dont think its an nvidia problem.
Also i think its only a problem with opengl games when using wayland. I tested it with Factorio when using wayland which also doesnt work but it doesnt crash. I also tried minecraft with the vulkan mod and there it works fine on wayland.

I hope that helps

**Comment by MrSn0wy** [comment]
Okay i tried a few things and here are the results:
- built-in (3.3) glfw using  x11 (or **X**wayland) works fine.
- vulkanmod on x11 & wayland works fine.
- native (newest) glfw (built for x11) using x11 (or **X**wayland) works fine.
- native (newest) glfw (built for wayland) using wayland crashes.

This seems to be an issue (like Znojmok said) with opengl on wayland *(using obs-vkcapture)*.

**Comment by Fxzzi** [comment]
i've actually noticed this as well, I thought it was an issue with my setup. Any updates on this?

**Comment by umbrageodotus** [comment]
Any updates? Could be the exact same issue I have.

**Comment by umbrageodotus** [comment]
Happens on Intel Xe integrated graphics, too.

**Comment by dylanwulf** [comment]
I can confirm this issue is not specific to Nvidia. I have an AMD GPU and I have the same problem. Does not work when using Wayland, but works fine when I force Minecraft to run in Xwayland/X11 (setting env variable `XDG_SESSION_TYPE=x11` for minecraft seems to do the trick)

**Comment by dylanwulf** [comment]
I opened PR #297 which fixes the issue for me, would anyone else be able to confirm if it fixes their issue?
